### ISSUE TITLE
Field "tokenString" is missing in propOrder XmlType annotion of TokenStored

### ISSUE THREAD

**Issue by pkolb** [weblicht/wlfxb#16]
The class [TokenStored](https://github.com/weblicht/wlfxb/blob/master/src/main/java/eu/clarin/weblicht/wlfxb/tc/xb/TokenStored.java) has a field `tokenString` which is required by JAXB to be listed in the propOrder XmlType annotation in line 36 but isn't.
When I include a WLData object in my own class and try to write this encapsulating class as XML with JAXB marshaller the following error is thrown:
```
javax.xml.bind.JAXBException: 
Exception Description: The property or field tokenString on the class eu.clarin.weblicht.wlfxb.tc.xb.TokenStored is required to be included in the propOrder element of the XmlType annotation.
```
**Solution**:
[Line 36](https://github.com/weblicht/wlfxb/blob/master/src/main/java/eu/clarin/weblicht/wlfxb/tc/xb/TokenStored.java#L36) should be changed to:
`@XmlType(propOrder = {"end", "start", "tokenId", "tokenString"})`

**Comment by pkolb** [comment]
see [https://github.com/weblicht/wlfxb/pull/17](https://github.com/weblicht/wlfxb/pull/17)

**Comment by emanueldima** [comment]
closed by https://github.com/weblicht/wlfxb/pull/17
