### ISSUE TITLE
wlfxb 1.4.1 is not available on Maven Central

### ISSUE THREAD

**Issue by reckart** [weblicht/wlfxb#19]
wlfxb 1.4.1 is not available on Maven Central - the last version available there is 1.4.0

**Comment by emanueldima** [comment]
We just released 1.4.2 with additional tests and support for java 12, please let us know how it works: https://mvnrepository.com/artifact/eu.clarin.weblicht/wlfxb

**Comment by reckart** [comment]
Looks good, thanks!
