### ISSUE TITLE
wlfxb 1.4.0 fails if layers requested to preserve were not found

### ISSUE THREAD

**Issue by reckart** [weblicht/wlfxb#20]
With 1.3.3, one could merge data into a TCF file preserving whatever layers were in the original file. With the new 1.4.0, there is a check at the end of the `process()` method which makes the processing fail if any of the requested layers to be preserved could not be found:

```
        if (layersToRead.size() != readSucceeded.size()) {
            layersToRead.removeAll(readSucceeded);
            throw new WLFormatException("Following layers could not be read: " + layersToRead.toString());
        }
```

And unlike 1.3.3, any layers that were not in the `layersToRead` list are also not preserved with 1.4.0. This change in behavior is a problem since there is no way of knowing what is in the TCF file without reading it first - and of course when reading it as a stream, it cannot easily be read twice (besides the performance impact this would have).

It would be great if the functionality could be restored that one can merge data into a TCF file without having to request the reading of layers one is not interested in - or at least not failing the processing if layers that were requested to read were not present in the input file.

**Comment by emanueldima** [comment]
Thanks for reporting this issue, I tried replicating it but I am not able to. On `wlfxb-1.4.0` I created a test which runs without any issues: 

````
        String INPUT_FILE = ...;      
        InputStream is = ...;
        String outfile = ...;
        OutputStream os = new FileOutputStream(outfile);
        TextCorpusStreamed tc = new TextCorpusStreamed(is, EnumSet.of(TextCorpusLayerTag.TOKENS, TextCorpusLayerTag.NAMED_ENTITIES), os, false);
        Assert.assertEquals(2, tc.getLayers().size());
        tc.close();
        assertEqualXml(INPUT_FILE, outfile);
````

I'm not the original creator of this library, but from what I understand the `layersToRead` parameter means what is being stored in memory (layers which are required by the user to be present in the input stream, without which the processing cannot take place) . However, the rest is not discarded but should be copied to the output stream unchanged. If the output is missing some xml, check that you closed the `TextCorpusStreamed` object (`tc.close()` above), to flush the file.

As far as I can see this behaviour is not new in 1.4.x, the code you mentioned is also present in `wlfxb-1.2.9`.

What is indeed missing is a way to specify that we'd like to read some layers in memory if they exist in the input file, but we don't depend on them and if they're missing then we should not throw any exception. However, I'm not sure this functionality would be much used if present.

**Comment by reckart** [comment]
I probably should have mentioned that I observed the described behavior using `TextCorpusStreamedWithReplaceableLayers`, not `TextCorpusStreamed`. In my case, I want in particular to merge new annotations into an already existing TCF file maintaining any metadata and layers from that file which I do not explicitly request to replace

**Comment by emanueldima** [comment]
I see that there is a test file for `TextCorpusStreamedWithReplaceableLayers`, which seems to work as intended. The input file contains 4 layers, but the test requires only one to be present and one to overwrite. The others remain unchanged. Could you take a look at it and tell me how it differs from what you want to do?

https://github.com/weblicht/wlfxb/blob/master/src/test/java/eu/clarin/weblicht/wlfxb/io/TextCorpusStreamedWithReplaceableLayersTest.java#L76

You can also see what the library is doing for each layer here: https://github.com/weblicht/wlfxb/blob/master/src/main/java/eu/clarin/weblicht/wlfxb/io/TextCorpusStreamedWithReplaceableLayers.java#L203

**Comment by reckart** [comment]
Hm... trying to show you in more detail what breaks I now have trouble to reproduce the issue - no idea why. So it seems to work as expected with 1.4.0. Sorry for the noise. I do have another question, but I'll open a separate issue. Thanks!
